### ISSUE TITLE
nose tests failing

### ISSUE THREAD

**Issue by jvidin** [openvenues/pypostal#4]
Trying to run the initial tests documented 
using >> nosetests postal/tests 
ERROR: Failure: ImportError (cannot import name '_expand')
ERROR: Failure: ImportError (cannot import name '_parser')
Any help ?

**Comment by thatdatabaseguy** [comment]
To run the tests from the source checkout, try building the library in place first (there's a note about it in the README):

```
python setup.py build_ext --inplace
```

If that doesn't work, let me know.

**Comment by jvidin** [comment]
Receiving this error , belleive this is windows related , any tips?
thanks
```
(3.4.4_pyenv) C:\PythonProjects\github-pypostal>python setup.py build_ext --inplace
running build_ext
building 'postal._expand' extension
error: Microsoft Visual C++ 10.0 is required (Unable to find vcvarsall.bat).
```

**Comment by thatdatabaseguy** [comment]
Ah, libpostal hasn't been tested on Windows yet, but reports so far are that the underlying C library doesn't compile on Windows because of the use of mmap. I don't have access to any Windows machines, but am willing to accept patches.

It also looks like you might not have a C compiler on that machine. Were you able to get [libpostal](https://github.com/openvenues/libpostal) to compile before installing the Python lib?

**Comment by kennydurell** [comment]
Hey, I'm very excited to use libpostal to help fill out addresses for a fire risk project I'm working on. 

Everything in the readme has proceeded smoothly up to the nosetests install and I have 2 questions about it (I'm a novice coder so I apologize if the solution is a simple one). 

1. Should I be in the scripts folder of the libpostal folder I'm doing all of these installations from? It looks like the setup.py file is in there. 

2. I'm getting the following error message when I try to run the ' python setup.py build_ext --inplace' within the scripts folder:

error: unable to open output file 'build/temp.macosx-10.7-x86_64-2.7/scripts/../src/scanner.o':
      'No such file or directory'
1 error generated.
error: command 'gcc' failed with exit status 1

**Comment by thatdatabaseguy** [comment]
Hey @kennydurell,

So the `scripts` dir in the main libpostal repo is a collection of tools to help train the libpostal models, and it happens to be written in Python (the language I personally use most often in addition to C). This repo contains the Python bindings to libpostal which allow you to parse and normalize street addresses in Python by calling the libpostal C functions and then converting input/output to & from Python types e.g. unicode strings that can be used in your application.

The nose tests can be run one of two ways:

1. Go to your local checkout of this repo, and run `python setup.py build_ext --inplace`
2. From this repo's checkout, `cd postal` and then run `nosetests tests/` (or go to any directory on the system other than the top level of this repo and run `nosetests $YOUR_CHECKOUT_DIR/postal/tests`)

This mostly has to do with Python's module search path order. Because there's a directory named `postal` in this repo and the installed module is also named `postal`, you can't run the nose tests from the top directory of this repo, which is the natural place most people would want to run them to check that the installation worked. This is because when you do `from postal.parser import parse_address`, Python will first see the local directory called `postal` with an `__init__.py` in it, and use that local module instead of the on in your installed packages. In a pure-Python library, this wouldn't be an issue as long as the checkout and the installed library were the same version, but because we use C extensions, they need to be compiled before they can be imported. A `setup.py install` or a `pip install` will effectively build the extensions in a temporary directory, then install everything in your site-packages, whereas with `python setup.py build_ext --inplace`, the extension modules are built directly in the checkout dir.
