### ISSUE TITLE
Release on pypi.python.org

### ISSUE THREAD

**Issue by leture** [openvenues/pypostal#5]
Hi,

is there a release on pypi.python.org planned because this would be very convenient so that pip can be used to install the package and listing in requirements files can be done easily. At the moment a release on pypi.python.org would be blocked by a name clash with the already existing package https://pypi.python.org/pypi/pyPostal.

Best regards

**Comment by thatdatabaseguy** [comment]
:tada: https://pypi.python.org/pypi/postal

Because of the name conflict, I changed the package name to just "postal" (which is already the name you import when using the library). Strangely that name wasn't taken on PyPI.

Note that libpostal will still have to be installed separately (similar to say having to install libxml2 before lxml). Ideally I'd like to get it to work with one command, may be possible with a wheel distribution.

**Comment by leture** [comment]
Thank you very much!

**Comment by merwok** [comment]
FYI mainstream wheel tooling is not designed to handle system (C) libraries, but there are people working on using the wheel format to do that.
