### ISSUE TITLE
ImportError: cannot import name _parser

### ISSUE THREAD

**Issue by rbrtmrtn** [openvenues/pypostal#6]
If I install the package with `python setup.py install` I get an `ImportError: cannot import name '_parser'`. If I `python setup.py develop` however, it works.

This is on Ubuntu using Python 2.7.6 or 3.4.3.

**Comment by thatdatabaseguy** [comment]
That has to do with Python's import order and only happens when importing from the source checkout directory.

There's a package called "postal" at the root of the repo. If you run ```python setup.py install``` from a source checkout, setup.py builds the C extensions (_expand.so and _parser.so) in a temporary build directory and then copies that into your site-packages. However, when trying to import one of the modules from that same checkout dir, Python will import the local package before checking site-packages, and the local package doesn't have the required C extensions. When running ```python setup.py develop``` or ```python setup.py build_ext --inplace```, the C extensions are built in-place.

The recommended way to install pypostal is either to use pip (it's on PyPI now so ```pip install postal``` does the trick, although the libpostal C library needs to be installed separately) or when running tests/developing locally, to use ```python setup.py develop``` as you mentioned.

**Comment by rbrtmrtn** [comment]
The `pip install` worked great, thanks!
